In [2]:
import numpy as np

In [2]:
'''
版本号
'''

np.__version__

'1.16.6'

In [3]:
'''
配置说明
'''

np.show_config

<function numpy.__config__.show()>

In [4]:
'''
创建长度为10的零向量
'''

z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
'''
统计numpy数组
'''

z = np.zeros((10, 10))
z.size

100

In [6]:
'''
查看numpy函数文档
'''

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [7]:
'''
创建⼀个值域范围从10到49的向量
'''
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
'''
反转⼀个向量
'''

z = np.arange(10)
z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
'''
创建⼀个 3x3 并且值从0到8的矩阵
'''

z = np.arange(9).reshape(3, 3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
'''
找到数组[1,2,0,0,4,0]中⾮0元素的位置索引 
'''

z = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(z)

(array([0, 1, 4], dtype=int64),)

In [11]:
'''
创建⼀个 3x3 的单位矩阵
'''

z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
'''
创建⼀个 3x3x3的随机数组 
'''

z = np.random.random((3, 3, 3))
z

array([[[0.34857421, 0.12955247, 0.42281645],
        [0.76812309, 0.01532934, 0.08568514],
        [0.14046187, 0.04290908, 0.62750625]],

       [[0.03795485, 0.48955415, 0.41708803],
        [0.6104827 , 0.65141274, 0.70979523],
        [0.24651069, 0.95920946, 0.56659572]],

       [[0.3980433 , 0.92701053, 0.2481323 ],
        [0.16531971, 0.33641306, 0.15495788],
        [0.63030571, 0.01583589, 0.64808605]]])

In [13]:
'''
创建⼀个 10x10 的随机数组并找到它的最⼤值和最⼩值 
'''

z = np.random.random((10, 10))
z.max(), z.min()

(0.9887984026011524, 0.0035983682889649815)

In [14]:
'''
创建⼀个⻓度为30的随机向量并找到它的平均值
'''

z = np.random.random(30)
z.mean()

0.5240091383884838

In [16]:
'''
创建⼀个⼆维数组，其中边界值为1，其余值为0
'''

z = np.ones((5, 5))
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
'''
对于⼀个存在在数组，添加⼀个⽤0填充的边界
'''

z = np.ones((5, 5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [19]:
'''
涉及NaN的操作
'''

0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, 0.3 == 3 * 0.1

(nan, False, False, nan, False)

In [24]:
'''
创建⼀个 5x5的矩阵，并设置值1,2,3,4落在其对⻆线下⽅位置
'''

temp = np.arange(4)
z = np.diag(1 + temp, k=-1)
z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [26]:
'''
创建⼀个8x8 的矩阵，并且设置成棋盘样式
'''

Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
'''
考虑⼀个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么
'''

np.unravel_index(100, (6, 7, 8))   # 多维数组与连续内存索引的转化

(1, 5, 4)

In [ ]:
'''
⽤tile函数去创建⼀个 8x8 的棋盘样式矩阵
'''

# tile 复制函数
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

In [28]:
np.info(np.tile)  

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [29]:
'''
对⼀个5x5的随机矩阵做归⼀化
'''

z = np.random.random((3, 3))
z_new = (z - z.min()) / (z.max() - z.min())
z_new

array([[0.        , 0.41774296, 0.16910651],
       [0.36275058, 0.54498691, 0.77137834],
       [0.9517334 , 1.        , 0.16152509]])

In [32]:
'''
创建⼀个将颜⾊描述为(RGBA)四个⽆符号字节的⾃定义dtype
'''

color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [33]:
'''
⼀个5x3的矩阵与⼀个3x2的矩阵相乘，实矩阵乘积是什么？
'''

A = np.ones((5, 3))
B = np.ones((3, 2))
z = np.dot(A, B)
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [38]:
'''
给定⼀个⼀维数组，对其在3到8之间的所有元素取反
'''

z = np.arange(11)
z[((z > 3) & (z < 8))] *= -1  # & 不是 and
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [41]:
'''
脚本运⾏后的结果
'''

np.sum(range(5),-1) #求取range的和

10

In [42]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same pr

In [45]:
'''
从零位对浮点数组做舍⼊ 
'''

z = np.random.uniform(-10, 10, 5)
print(z)
print(np.abs(z))
print(np.ceil(np.abs(z)))

[-4.61095486  3.15574963  9.17634581 -2.86211602  5.74886378]
[4.61095486 3.15574963 9.17634581 2.86211602 5.74886378]
[ 5.  4. 10.  3.  6.]


In [46]:
np.info(np.copysign)

copysign(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Change the sign of x1 to that of x2, element-wise.

If both arguments are arrays or sequences, they have to be of the same
length. If `x2` is a scalar, its sign will be copied to all elements of
`x1`.

Parameters
----------
x1 : array_like
    Values to change the sign of.
x2 : array_like
    The sign of `x2` is copied to `x1`.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only

In [47]:
'''
找到两个数组中的相同元素
'''

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(Z1, Z2)
print(np.intersect1d(Z1, Z2))

[8 8 6 0 8 0 3 3 0 0] [9 2 2 0 7 5 7 3 8 0]
[0 3 8]


In [3]:
'''
如何直接在位计算(A+B)*(-A/2)
'''

A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
A

array([-1.5, -1.5, -1.5])

In [5]:
'''
⽤五种不同的⽅法去提取⼀个随机数组的整数部分
'''

Z = np.random.uniform(0, 10, 10)
print(Z)
print(Z - Z % 1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[6.46101236 7.21495757 5.95922142 9.25227519 0.45620603 7.70485759
 6.64262995 5.42802371 9.61021844 7.34387422]
[6. 7. 5. 9. 0. 7. 6. 5. 9. 7.]
[6. 7. 5. 9. 0. 7. 6. 5. 9. 7.]
[6. 7. 5. 9. 0. 7. 6. 5. 9. 7.]
[6 7 5 9 0 7 6 5 9 7]
[6. 7. 5. 9. 0. 7. 6. 5. 9. 7.]


In [6]:
'''
创建⼀个5x5的矩阵，其中每⾏的数值范围从0到4
'''

z = np.zeros((5, 5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [7]:
'''
通过考虑⼀个可⽣成10个整数的函数，来构建⼀个数组
'''


def generate():
    for x in range(10):
        yield x


Z = np.fromiter(generate(), dtype=float, count=-1)  # np.fromiter从可迭代对象创建新的1维数组
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
'''
创建⼀个⻓度为10的随机向量，其值域范围从0到1，但是不包括0和1
'''

Z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [11]:
'''
创建⼀个⻓度为10的随机向量，并将其排序
'''

Z = np.random.random(10)
Z.sort()
print(Z)

[0.21835253 0.24193229 0.42864048 0.46341918 0.67499229 0.71863545
 0.77264585 0.77606098 0.80621024 0.90868621]


In [12]:
'''
对于⼀个⼩数组，如何⽤⽐ np.sum更快的⽅式对其求和
'''

Z = np.arange(10)
np.add.reduce(Z)

45

In [15]:
'''
对于两个随机数组A和B，检查它们是否相等
'''

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
A == B, equal

(array([ True, False, False,  True,  True]), False)

In [16]:
'''
将笛卡尔坐标下的⼀个10x2的矩阵转换为极坐标形式
'''

Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.77684242 1.002391   0.92931203 0.25608874 0.61195086 1.07630653
 0.86041586 0.74378884 0.52272335 0.60983292]
[0.08119421 1.07264244 0.89636601 1.19119587 0.5188462  0.71351378
 0.2073143  1.22843899 1.54570887 0.16171908]


In [3]:
'''
创建⼀个⻓度为10的向量，并将向量中最⼤值替换为1
'''

Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.73703369, 0.52024415, 0.66669558, 0.        , 0.6124947 ,
       0.38718882, 0.13479273, 0.75400375, 0.63527274, 0.58064788])

In [3]:
'''
创建⼀个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
'''

Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]
