## Tensor张量

In [1]:
import torch
import numpy as np

### 张量类型转化

In [6]:
'''
创建新的tensor 默认为FloatTensor
'''

a = torch.Tensor(2, 2) # torch.Tensor等价于torch.FloatTensor
print(a)

tensor([[1.0033e-42, 0.0000e+00],
        [1.0033e-42, 0.0000e+00]])


In [7]:
'''
tensor数据类型转化
'''

b = a.int()   # int()  float()   double()
print(b)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)


In [8]:
'''
使用type函数
'''

c = b.type(torch.FloatTensor)
c

tensor([[0., 0.],
        [0., 0.]])

In [16]:
'''
使用type_as()保持类型一致
'''
c = torch.Tensor(4, 4)
print(c)
d = c.type_as(b)
print(d)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.0459e-42, 0.0000e+00],
        [0.0000e+00, 1.0745e-38, 0.0000e+00, 9.3674e-39]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


### 随机张量的创建

In [3]:
# 使用python列表list创建
a = torch.Tensor([[1, 2], [3, 4]])
#print(a)

# 使用zeros函数创建零张量
b = torch.zeros(2, 2)
#print(b)

# 使用ones函数创建全1张量
c = torch.ones(2, 2)
#print(c)

# 创建对角线全1张量
d = torch.eye(2, 2)
#print(d)

# 创建服从正态分布的随机张量
e = torch.randn(2, 2)
#print(e)

# 创建连续整数向量
f = torch.arange(12)
#print(f)

# 生成随机排列张量
g = torch.randperm(4)
#print(g)

# 生成范围内整数的随机数
h = torch.randint(10, (3, 4))
#print(h)

tensor([[1., 2.],
        [3., 4.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0.],
        [0., 1.]])
tensor([[0.5089, 1.3943],
        [0.1924, 0.2655]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([3, 1, 2, 0])
tensor([[4, 2, 7, 4],
        [3, 8, 7, 8],
        [9, 0, 5, 5]])


### torch张量与list列表、numpy数组的转化

In [32]:
'''
tensor <-> list
'''

a = [1, 2, 3]
b = torch.tensor(a)  ## list to tensor
# print(id(a),id(b)) 不相同
#print(a)
#print(b)

c = b.tolist()      # tensor to list
#print(c)

[1, 2, 3]
tensor([1, 2, 3])
[1, 2, 3]


In [34]:
'''
tensor <-> numpy
'''

a = np.array([1, 2, 3])  
#print(a)

b = torch.from_numpy(a)   # numpy to tensor
#print(b)

c = b.numpy()             # tensor to numpy
#print(c)

[1 2 3]
tensor([1, 2, 3], dtype=torch.int32)
[1 2 3]


### 张量属性获取（维度，元素数量）

In [37]:
'''
维度获取
'''
t = torch.Tensor(2, 2)
print(t.shape)
print(t.size())

torch.Size([2, 2])
torch.Size([2, 2])


In [38]:
'''
获取元素总数
'''

t=torch.arange(12)
t.numel()

12

### 张量的组合与分块

In [11]:
'''
基于torch.cat()在已有维度添加数据
'''
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
#print(a.shape)
b = torch.arange(6, 12).reshape(2, 3).float()
#print(b)
#print(b.shape)

c = torch.cat([a, b], 0)
#print(c.shape)
d = torch.cat([a, b], 1)
#print(d)
#print(d.shape)

torch.Size([2, 3])
tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([2, 3])
torch.Size([4, 3])
tensor([[ 1.,  2.,  3.,  6.,  7.,  8.],
        [ 4.,  5.,  6.,  9., 10., 11.]])
torch.Size([2, 6])


In [13]:
'''
基于torch.stack()扩展维度添加数据
'''
t1 = torch.randn(3, 3)
t2 = torch.arange(9).reshape(3, 3).float()
t = torch.stack([t1, t2], 0)
print(t.shape)
print(t)

torch.Size([2, 3, 3])
tensor([[[-0.9154,  0.7221, -0.2612],
         [ 0.9302, -1.8321,  1.4481],
         [-0.3382,  0.1383, -1.7269]],

        [[ 0.0000,  1.0000,  2.0000],
         [ 3.0000,  4.0000,  5.0000],
         [ 6.0000,  7.0000,  8.0000]]])


In [14]:
t = torch.stack([t1, t2], 1)
print(t.shape)
print(t)

torch.Size([3, 2, 3])
tensor([[[-0.9154,  0.7221, -0.2612],
         [ 0.0000,  1.0000,  2.0000]],

        [[ 0.9302, -1.8321,  1.4481],
         [ 3.0000,  4.0000,  5.0000]],

        [[-0.3382,  0.1383, -1.7269],
         [ 6.0000,  7.0000,  8.0000]]])


In [15]:
t = torch.stack([t1, t2], 2)
print(t.shape)
print(t)

torch.Size([3, 3, 2])
tensor([[[-0.9154,  0.0000],
         [ 0.7221,  1.0000],
         [-0.2612,  2.0000]],

        [[ 0.9302,  3.0000],
         [-1.8321,  4.0000],
         [ 1.4481,  5.0000]],

        [[-0.3382,  6.0000],
         [ 0.1383,  7.0000],
         [-1.7269,  8.0000]]])


In [18]:
'''
使用torch.chunk()函数对张量指定数量进行分块
'''

a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
b = torch.chunk(a, 2, 0)  # 将张量a沿着第0维分成2块
print(b)

(tensor([[1., 2., 3.]]), tensor([[4., 5., 6.]]))


In [52]:
'''
使用torch.split()对张量指定大小进行拆分
'''

c = torch.split(a, [1, 2], 1) # 对张量a沿着第1维按照[1,2]分块
print(c)

(tensor([[1.],
        [4.]]), tensor([[2., 3.],
        [5., 6.]]))


### Tensor的索引与变形

In [53]:
'''
通过下标索引
'''
a = torch.Tensor([[1, 0], [3, 2]])

print(a[1])
print(a[1,1])

tensor([3., 2.])
tensor(2.)


### 依据条件表达式获取元素及索引

In [3]:
'''
使用逻辑表达式进行索引
'''

t = torch.randn(2, 2)
print(t)
print(t[t > 0]) # 取出索引并拉成一维张量 等价于 torch.masked_select(t,t>0)

tensor([[ 0.8657, -0.5027],
        [ 0.4255,  0.3918]])
tensor([0.8657, 0.4255, 0.3918])


In [9]:
'''
比较运算
'''

# 等于运算索引

x = torch.randint(3, (3, 3))
index_eq = torch.eq(x, 2)

# 大于运算
index_gt = torch.gt(x, 1)

# 小于运算
index_lt = torch.lt(x, 2)

# 大于等于
index_ge = torch.ge(x, 2)

index_t = x == 2

index_eq, index_gt, index_lt, index_ge, index_t

(tensor([[1, 0, 0],
         [0, 1, 1],
         [1, 0, 0]], dtype=torch.uint8), tensor([[1, 0, 0],
         [0, 1, 1],
         [1, 0, 0]], dtype=torch.uint8), tensor([[0, 1, 1],
         [1, 0, 0],
         [0, 1, 1]], dtype=torch.uint8), tensor([[1, 0, 0],
         [0, 1, 1],
         [1, 0, 0]], dtype=torch.uint8), tensor([[1, 0, 0],
         [0, 1, 1],
         [1, 0, 0]], dtype=torch.uint8))

In [6]:
torch.masked_select(t, t > 0)

tensor([0.8657, 0.4255, 0.3918])

In [4]:
'''
选择非零的元素下标索引，查元素可通过前述方法
'''
t = torch.Tensor([[1, 0, 2], [0, 0, 3]])
non0 = torch.nonzero(t) # 返回的是索引！！
print(non0)

tensor([[0, 0],
        [0, 2],
        [1, 2]])


In [11]:
t = torch.masked_select(t, t != 0)
t

tensor([1., 2., 3.])

In [5]:
'''
定义tf.gather_nd函数
'''
def torch_gather_nd(x, coords):
    x = x.contiguous()
    inds = coords.mv(torch.LongTensor(x.stride()))
    x_gather = torch.index_select(x.reshape(-1), 0, inds)
    return x_gather

In [6]:
nonx=torch_gather_nd(t,non0)
nonx

tensor([1., 2., 3.])

In [16]:
'''
torch.where(condition,x,y)  满足condition输出x，不满足输出y
'''

t = torch.tensor([[1, 2, 3], [4, 5, 6]])
t1 = torch.where(t > 3, torch.full_like(t, 1), t)
print(t1)

tensor([[1, 2, 3],
        [1, 1, 1]])


In [17]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.where(t > 3, torch.tensor(1,dtype=torch.long), t)
t2

tensor([[1, 2, 3],
        [1, 1, 1]])

In [5]:
'''
使用clamp函数对元素限制
'''

t = torch.arange(6).reshape(2,3)
t.clamp(1,4) # 小于1的数为1 大于4的数为4

tensor([[1, 1, 2],
        [3, 4, 4]])

### 张量变形

In [24]:
a = torch.arange(6)
print(a)

tensor([0, 1, 2, 3, 4, 5])


In [25]:
'''
使用view()
'''

b = a.view(2, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [26]:
'''
使用reshape
'''

c = a.reshape(3, 2)
c

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [27]:
'''
resize_进行原地操作
'''

d = a.resize_(2, 3)
d

tensor([[0, 1, 2],
        [3, 4, 5]])

### 张量维度变换

In [11]:
'''
使用transpose进行两个维度的转置 注意只有两个维度可变！！
'''

a = torch.randn(2, 3, 4)
b = a.transpose(1, 2)
print(b.shape)

torch.Size([2, 4, 3])


In [31]:
'''
使用permute进行多维度转置
'''

a = torch.randn(2, 3, 4, 4)
print(a)
b = a.permute(1, 0, 2, 3)
print(b.shape)

tensor([[[[-1.8326e+00,  3.0995e-01, -5.8632e-01, -7.8512e-01],
          [-7.6643e-01, -1.6678e-01, -1.8480e-01,  4.8551e-01],
          [ 9.4620e-01,  6.9529e-01,  2.6464e-01,  3.7948e-01],
          [-8.8412e-01,  8.8079e-01, -7.8480e-02, -1.7295e+00]],

         [[ 2.0035e-01,  1.4955e+00, -1.5980e+00,  1.2968e+00],
          [-1.2007e+00,  2.3130e-01,  7.7936e-02, -7.8087e-01],
          [-1.2616e+00, -1.5478e+00,  3.2053e-01, -3.6779e-01],
          [-9.7553e-02, -4.7623e-01, -2.8041e-01,  8.3581e-01]],

         [[-1.1460e+00,  1.2939e-01, -1.0328e+00, -4.7575e-01],
          [-1.5065e+00, -5.0245e-01, -4.7354e-01,  1.7148e+00],
          [ 8.0770e-01, -3.4655e-02,  1.6937e+00, -1.3660e+00],
          [ 5.5628e-01, -2.5619e-01,  5.6245e-01,  9.5372e-02]]],


        [[[ 8.9207e-01, -7.2033e-02, -9.9900e-01, -8.3959e-01],
          [-1.3506e-01,  1.5266e+00,  3.3313e-01, -5.3554e-01],
          [ 5.3303e-02, -9.5044e-01, -2.6120e+00,  5.8022e-01],
          [ 2.6052e+00, -5.1532e

In [30]:
'''
squeeze去除维度为1的维度
'''

a=torch.randn(1,3,4,4)
b=a.squeeze(0) # 去除第0维度的1
b.shape

torch.Size([3, 4, 4])

In [17]:
'''
unsqueeze增加维度
'''

a = torch.randn(3, 4, 4)
b = a.unsqueeze(0)
print(b.shape)

torch.Size([1, 3, 4, 4])


In [32]:
'''
使用expand复制相应维度 1 ->n
'''

t = torch.randn(1, 3, 3)
print(t)
t_ex = t.expand(3, 3, 3)
print(t_ex)
print(t_ex.shape)

tensor([[[ 1.5565, -0.5176, -0.6837],
         [ 1.4660, -0.9521,  1.1106],
         [-0.2141,  1.5363, -1.2925]]])
tensor([[[ 1.5565, -0.5176, -0.6837],
         [ 1.4660, -0.9521,  1.1106],
         [-0.2141,  1.5363, -1.2925]],

        [[ 1.5565, -0.5176, -0.6837],
         [ 1.4660, -0.9521,  1.1106],
         [-0.2141,  1.5363, -1.2925]],

        [[ 1.5565, -0.5176, -0.6837],
         [ 1.4660, -0.9521,  1.1106],
         [-0.2141,  1.5363, -1.2925]]])
torch.Size([3, 3, 3])


### 张量的排序与最值

In [2]:
a = torch.randn(3, 3)
#print(a)

tensor([[-1.8379,  1.5234,  0.3487],
        [-1.4017, -2.5192,  1.4343],
        [ 0.5637,  0.6419, -0.4996]])


In [5]:
'''
使用sort函数进行排序，返回排序后的值及索引
'''

b, indexes = a.sort(0, True)  # 按行进行排序，即按照列进行比较，True代表降序（从大到小）
#print(b)

tensor([[ 0.5637,  1.5234,  1.4343],
        [-1.4017,  0.6419,  0.3487],
        [-1.8379, -2.5192, -0.4996]])


In [6]:
indexes  # 按从大到小的顺序进排序的索引

tensor([[2, 0, 1],
        [1, 2, 0],
        [0, 1, 2]])

In [8]:
'''
使用max与min函数指定维度选择最值，返回最值以及对应索引
'''

c , index = indexes.max(0)  # 按行选择最大值，即选择每列最值
print(c)

tensor([2, 2, 2])


In [9]:
index

tensor([0, 1, 2])

### 张量的广播

In [22]:
'''
广播就是从尾部遍历维度，两个张量的维度对应的只能是1或者不存在
'''

a = torch.ones(3, 1, 2)
b = torch.ones(2, 1)
c = a + b
print(c.shape)  # 维度结果取两个张量各维度的最大值

torch.Size([3, 2, 2])


### 原地操作_

In [10]:
a = torch.tensor([[1, 2], [3, 4]])
b = a.add_(a)  # 加_表示原地操作
print(b)

tensor([[2, 4],
        [6, 8]])


### Autograd自动求导

In [4]:
a = torch.randn(2, 2, requires_grad=True)
b = torch.randn(2, 2)

In [5]:
print(a)
print(b)

tensor([[-0.4364,  1.0122],
        [-0.1160, -1.2081]], requires_grad=True)
tensor([[ 0.0917, -1.1998],
        [-0.1489, -1.4336]])


In [13]:
'''
requires_grad
'''

print(a.requires_grad)
print(b.requires_grad)

True
False


In [14]:
'''
使用内置requires_grad_()将tensor变为需要求导 即将 requires_grad=True
'''

b.requires_grad_()

tensor([[-1.3295,  0.6521],
        [ 0.2530,  0.1194]], requires_grad=True)

In [15]:
'''
通过requires_grad查看是否需要求导属性
'''

c = a + b
print(c.requires_grad)

True


In [27]:
'''
使用grad_fn查看张量创建方式
'''

print(a.grad_fn)
print(b.grad_fn)
print(c.grad_fn)

None
None


In [31]:
'''
使用detach()查看张量值
'''

c.detach()  ## 等同于早期版本的data 更安全，生成的新数据默认为False

tensor([[ 1.6273,  0.7909],
        [ 0.2451, -0.6679]])

### 计算图

In [17]:
'''
创建计算图 y=ax+b
'''

# 初始化变量
x = torch.randn(1)
w = torch.ones(1, requires_grad=True)
b = torch.ones(1, requires_grad=True)

In [18]:
'''
自己手动创建的都是叶子节点
'''
print(x.is_leaf)
print(w.is_leaf)
print(b.is_leaf)

True
True
True


In [19]:
'''
前向计算
'''

y = w * x
z = y + b

In [20]:
'''
由计算生成的都不是叶子节点
'''

print(y.is_leaf)
print(z.is_leaf)

False
False


In [21]:
'''
对最终结果采用反向传播，通过grad获取梯度
'''

z.backward(retain_graph=True)  # 保证梯度不需要叠加
print(w.grad)
print(b.grad)

tensor([0.8339])
tensor([1.])


### 张量矩阵运算

In [4]:
'''
矩阵点乘 torch.mul()函数
'''

a = torch.full((3, 3), 2)
b = torch.randint(9, (3, 3)).float()
print(a)
print(b)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 7., 2.],
        [0., 0., 0.],
        [3., 6., 8.]])


In [6]:
c = a.mul(b)
c

tensor([[ 0., 14.,  4.],
        [ 0.,  0.,  0.],
        [ 6., 12., 16.]])

In [9]:
'''
矩阵乘法（内积运算） 只适用于低维情形
'''

A = torch.arange(12).reshape(3, 4).float()
B = torch.randn(4, 3)
C = torch.mm(A, B)
C

tensor([[ -1.4354,   2.1790,   2.2766],
        [-10.7198,   2.3536,   5.8722],
        [-20.0043,   2.5282,   9.4678]])

In [11]:
'''
多维矩阵乘法
'''

A = torch.arange(12).reshape(3, 4).float()
B = torch.randn(4, 3)
C = torch.matmul(A, B)
C

tensor([[ -3.4689,  -2.2716,   1.7884],
        [-12.0591,  -7.2039,   2.9889],
        [-20.6494, -12.1362,   4.1893]])