## Tensor理论

Tensor 概念：

是一个高维数组，是标量，向量，矩阵的高维扩展



![](./img/tensor.png)

**Tensor与Variable的关系：**

注意：0.4.0以后的pytorch已经将Variable并入了Tensor，所以Variable已经不常用

作用：
- 主要用于封装tensor，用于自动求导
- 来源于torch.autograd

数据结构属性：
- detach()

    用于封装的tensor数据
    
- grad

    数据的梯度
    
- grad_fn 

    创建Tensor的function
    
- require_grad 

    布尔值，是否需要梯度
    
- is_leaf 

    布尔值，指示是否是叶子节点（张量,用于计算图）

![](./img/variable.png)

Tensor数据属性：（0.4.0版本以后）

- 继承来自于Variable的所有数据属性（data,grad,grad_fn,require_grad,is_leaf）
- dtype 

    张量数据类型，如torch.FloatTensor 或者 torch.cuda.FloatTensor（用于输入数据） 或者 torch.long (用于标签)
    
- shape 

    张量形状，如（64,64,224,224）
    
- device

    张量所在设备，指明在GPU和CPU设备

![](./img/tensorshu.png)

In [1]:
'''
导入pytorch
'''

import torch
import numpy as np

In [2]:
# ===============================  exmaple 2 ===============================
# 通过torch.tensor创建张量

t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#等价输出
print(t.detach())
print(t.dtype)

print(t.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64
torch.Size([3, 3])


## 张量创建

**1. 直接创建法**

    torch.tensor(data,dtype=None,device=None,requires_grad=False,pin_memory=False)

- data可以是list或者numpy
- 注意：pin_memory表示是否用于锁页内存
- device可选cuda或者cpu

In [6]:
# ===============================  exmaple 2 ===============================
# 通过torch.tensor创建张量

alist = [1, 2, 4, 5, 6]

list_to_tensor = torch.tensor(alist)
print(list_to_tensor.dtype)

ndarray = np.ones((3, 3))
numpy_to_tensor = torch.tensor(ndarray, device='cpu')  #由于本版本支持cuda
#numpy_to_tensor = torch.tensor(ndarray, device='cuda')
numpy_to_tensor.device
#numpy_to_tensor

torch.int64
cpu
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


**2. 从numpy到Tensor**

    torch.from_numpy(numpy_array)

- 功能

    从numpy_array创建Tensor

- 注意
    
    numpy_array和Tensor共享同一块内存，改动一个，另一个也变


![](./img/numpy.png)

In [8]:
# ===============================  exmaple 3 ===============================
# 通过torch.from_numpy创建张量

array = np.array([[1, 2, 3], [4, 5, 6]])
#print(array)
array_to_tensor = torch.from_numpy(array)
#print(array_to_tensor)
array_to_tensor[0, 0] = 100
#print(array_to_tensor)
#print(array)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[100,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)
[[100   2   3]
 [  4   5   6]]


**3. 依据数值创建Tensor**


**3.1 全0张量**

    torch.zeros(size,out=None,dtype=None,layout=torch.strided,device=None,requires_grad=False)

功能：
    依据size创建全0向量

- size 

    张量形状

- out

    输出结果

- layout

    内存布局形式，有strided,sparse_coo
    
- device

    cpu,cuda
  
- requires_grad

    是否需要梯度




    torch.zeros_like(input,dtype=None,layout=None,device=None,requires_grad=False)

功能：
    依据input形状创建全0张量

- input
    
    创建与input形状一样的全0向量

In [12]:
# ===============================  exmaple 4 ===============================
# 通过torch.zeros创建张量

t = torch.zeros((3, 3))
print(t)

# ===============================  exmaple 5 ===============================
# 通过torch.zeros_like()创建张量

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t = torch.zeros_like(t1, dtype=torch.float64)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


**3.2 全1张量**

    torch.ones(size, dtype, device=None, requires_grad=False)


    torch.ones_like(input,dtype,device=None,requires_grad=False)

In [14]:
# ===============================  exmaple 6 ===============================
# 通过torch.ones() 和 torch.ones_like()创建全1张量

t_one = torch.ones((5, 5))

t_test = torch.zeros((4, 3))

t_one_like = torch.ones_like(t_test)

print(t_one_like)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


**3.3  自定义全值张量**

    torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

- full_value

    全张量的值

    
    
    torch.full_like(input,fill_value)

In [17]:
# ===============================  exmaple 7 ===============================
# 通过torch.full创建全值张量

#全10张量

t_10 = torch.full((5, 5), fill_value=10)
print(t_10)

t_test = torch.ones((2, 2))
t_12 = torch.full_like(t_test, fill_value=12)
print(t_12)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])
tensor([[12., 12.],
        [12., 12.]])


**3.4 等差（比）张量**

       torch.arange(start=0,end,steps=1,out=None,dtype=None,layout=torch.strided,device=None,requires_grad=False)

- 功能
    
    生成一维的等差张量，区间为[start,end)
    
- start

    区间起始值

- end

    区间终止值

- step

    区间步长
    

    torch.linspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

- 功能
    
    创建1维等比张量

- start

    数列起始值

- end

    数列结束值

- steps

    数列长度


In [26]:
# ===============================  exmaple 8 ===============================
# 通过torch.arange()创建等差数列张量

#生成偶数张量

t_ou = torch.arange(2, 10, 2)
print(t_ou)

# ===============================  exmaple 9 ===============================
# 通过torch.linspace创建均分数列张量

t_q = torch.linspace(2, 32, 6)#(32-2)/6=5
print(t_q)

tensor([2, 4, 6, 8])
tensor([ 2.,  8., 14., 20., 26., 32.])


    torch.logspace(start, end, steps=100, base=10.0, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

- 功能

    创建对数均分的1维向量

- start 

    区间起始点

- end

    区间终止点


- steps

    区间长度

- base

    对数函数的基底，10

In [37]:
# ===============================  exmaple 10 ===============================
# 通过torch.logspace()创建均分数列张量

t=torch.logspace(2,4)  #[10^2,10^4]
print(t)

tensor([  100.0000,   104.7616,   109.7499,   114.9757,   120.4504,   126.1857,
          132.1941,   138.4886,   145.0829,   151.9911,   159.2283,   166.8101,
          174.7528,   183.0738,   191.7910,   200.9233,   210.4905,   220.5131,
          231.0130,   242.0128,   253.5364,   265.6088,   278.2559,   291.5052,
          305.3856,   319.9267,   335.1603,   351.1191,   367.8381,   385.3528,
          403.7016,   422.9243,   443.0621,   464.1590,   486.2601,   509.4139,
          533.6699,   559.0809,   585.7021,   613.5907,   642.8071,   673.4151,
          705.4805,   739.0723,   774.2636,   811.1310,   849.7534,   890.2148,
          932.6034,   977.0098,  1023.5306,  1072.2671,  1123.3243,  1176.8120,
         1232.8464,  1291.5498,  1353.0476,  1417.4736,  1484.9683,  1555.6766,
         1629.7510,  1707.3524,  1788.6499,  1873.8174,  1963.0402,  2056.5125,
         2154.4355,  2257.0188,  2364.4893,  2477.0769,  2595.0242,  2718.5876,
         2848.0361,  2983.6470,  3125.71

    torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires__grad=False)

- 功能

    创建单位对角矩阵

- n:行数

  m:列数

In [39]:
# ===============================  exmaple 11 ===============================
# 通过torch.eye()创建均分数列张量

torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

**4. 依概率分布生成张量**

**4.1 正态分布**

    torch.normal(mean, std, out=None)

    torch.normal(mean, std, size, out=None)

- 功能

    生成正态分布（高斯分布）

- mean

    均值

- std

    标准差

- 四种模式

mean为标量  std为标量

mean为标量  std为向量

mean为张量  std为标量

mean为张量  std为张量



In [40]:
# ===============================  exmaple 12 ===============================
# 通过torch.normal()创建正态分布张量

# mean：张量 std: 张量
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)

t_normal = torch.normal(mean, std)
print('mean:', mean)
print('std:', std)
print('t_normal', t_normal)

mean: tensor([1., 2., 3., 4.])
std: tensor([1., 2., 3., 4.])
t_normal tensor([ 0.6675, -2.4327,  2.4156,  2.7709])


In [48]:
# mean：标量 std: 标量
t_norm = torch.normal(0, 1, (4, ))  ##与3相同
t_norm2 = torch.normal(0, 1, (4, 1))
t_norm3 = torch.normal(0, 1, (1, 4))
print(t_norm)
print(t_norm2)
print(t_norm3)

tensor([ 0.6456, -0.3379,  0.3129, -0.0184])
tensor([[ 0.8450],
        [ 1.4252],
        [-0.0974],
        [ 0.7427]])
tensor([[-0.7797, -0.2071, -0.7629,  1.0192]])


In [52]:
# mean：张量 std: 标量
mean = torch.arange(1, 5, dtype=torch.float)
std = 1

t_norm = torch.normal(mean, std)  ##标准差都为1
print(t_norm)
print('mean:{}\nstd:{}'.format(mean, std))

tensor([ 0.4758, -0.5742,  3.5751,  4.4323])
mean:tensor([1., 2., 3., 4.])
std:1


**4.1 标准正态分布**

    torch.randn(size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

- 功能

    生成标准正态分布
    

    torch.randn_like(input)

In [53]:
# ===============================  exmaple 13 ===============================
# 通过torch.randn()创建正态分布张量

t = torch.randn((2, 3))
print(t)

tensor([[-0.7290,  1.0772, -0.3467],
        [ 0.4302, -0.8149,  0.9168]])


**4.2 均匀分布**

    torch.rand(size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

- 功能

    在[0,1)上生成均匀分布

     
    torch.rand_like(input)



In [56]:
# ===============================  exmaple 14 ===============================
# 通过torch.randn()创建均匀分布张量

t = torch.rand((3, 3))
print(t)

tensor([[0.6704, 0.6465, 0.3887],
        [0.6619, 0.9234, 0.4714],
        [0.7594, 0.3267, 0.1921]])


**自定义区间的均匀分布**

    torch.randint(low=0, high, size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

- 功能

    生成[low,high)的整数均匀分布

        torch.randint_like(input)



In [60]:
# ===============================  exmaple 15 ===============================
# 通过torch.randint()创建均匀分布整数张量

t = torch.randint(0,7,(4, 3))
print(t)

tensor([[0, 4, 0],
        [3, 3, 6],
        [6, 1, 0],
        [6, 6, 1]])


**4.3  生成随机排列**

    torch.randperm(n, out=None, dtype=torch.int6, layout=torch.strided, device=None, requires_grad=False)

- 功能
    
    生成0-n-1的随机全排列，充当了random.shuffle的功能（TensorFlow）

        torch.bernoulli(input, size, generator=None, out=None)

- 功能

    以input概率值生成两点概率分布
    
    注意input必须为张量

In [66]:
# ===============================  exmaple 16 ===============================

t=torch.randperm(5)

print(t)

t_ber=torch.bernoulli(torch.tensor([0.1,0.4,0.6]))
print(t_ber)

tensor([2, 3, 0, 4, 1])
tensor([0., 1., 0.])


## 张量的类型检测

In [5]:
t1 = torch.tensor([1, 2, 3])
print(isinstance(t1, torch.LongTensor))

True


In [7]:
t_gpu = t1.cuda()
print(isinstance(t_gpu, torch.cuda.LongTensor))

True


## 张量索引

In [2]:
'''
单个维度的索引
'''

a = torch.randn(4, 3, 28, 28)

print(a[0].shape)
print(a[0, 1].shape)
print(a[0, 1, 2, 4])

torch.Size([3, 28, 28])
torch.Size([28, 28])
tensor(-1.0117)


In [5]:
'''
冒号索引
:相当于->
'''

b = torch.rand(4, 3, 28, 28)

print(b[:2].shape)
print(b[:2, :1, :, :].shape)
print(b[:2, 1:].shape)

torch.Size([2, 3, 28, 28])
torch.Size([2, 1, 28, 28])
torch.Size([2, 2, 28, 28])


In [9]:
'''
使用冒号对所有图片等间隔采样，缩小为一半
'''

tens = torch.rand(4, 3, 28, 28)
tens_half = tens[:, :, 0:28:2, 0:28:2]  ##简要写法  tens_half = tens[:, :, ::2, ::2]
print(tens_half.shape)
#print(tens[,1].shape)  报错

torch.Size([4, 3, 14, 14])


In [6]:
'''
使用省略号...自适应维度
'''

print(tens[0,...].shape)  ## 等价于a[0]

print(tens[0,...,::2].shape)

torch.Size([3, 28, 28])
torch.Size([3, 28, 14])


## 张量小结测试

In [10]:
'''
创建标量
'''

t_scalar = torch.tensor(1.)
#t_vector=torch.tensor([1.])  ##创建向量
print(t_scalar)
print(t_scalar.shape)
print(t_scalar.size())
print(t_scalar.dim())  #dim=shape.shape

tensor(1.)
torch.Size([])
torch.Size([])
0


In [3]:
'''
向量常用于创建偏置以及线性层输入
'''

bias = torch.tensor([0])

In [7]:
'''
创建带批量为2的线性层一维输入
'''

input_tensor = torch.tensor([1, 2])
print(input_tensor.shape[0])

2


In [9]:
'''
创建批量为2的4维张量
'''

image_in = torch.rand(2, 3, 28, 28)
image_in

tensor([[[[3.8968e-01, 9.2057e-01, 8.0029e-01,  ..., 5.9498e-01,
           1.2399e-02, 4.6397e-01],
          [8.8366e-01, 2.3000e-01, 8.6891e-01,  ..., 4.6887e-01,
           2.1826e-01, 7.7907e-01],
          [9.1668e-01, 1.5556e-01, 6.9894e-01,  ..., 7.4492e-01,
           8.3081e-01, 8.0782e-01],
          ...,
          [1.9833e-01, 6.6708e-01, 4.8038e-01,  ..., 4.1517e-01,
           7.4727e-01, 7.5665e-01],
          [6.6790e-01, 5.2917e-01, 3.9979e-01,  ..., 9.5632e-01,
           2.8823e-01, 5.6313e-01],
          [4.2215e-01, 2.4959e-01, 6.9285e-02,  ..., 1.3289e-01,
           8.9725e-01, 9.0191e-01]],

         [[7.3643e-01, 4.7713e-01, 9.5669e-01,  ..., 4.0365e-01,
           4.7595e-01, 5.9045e-01],
          [8.1007e-01, 1.6429e-01, 2.9199e-01,  ..., 5.7358e-04,
           3.3748e-01, 5.3308e-01],
          [7.9939e-01, 3.8051e-01, 9.5043e-02,  ..., 2.1944e-01,
           3.1859e-01, 6.3576e-01],
          ...,
          [2.4095e-01, 4.7191e-01, 3.8380e-01,  ..., 5.2401

In [11]:
'''
获取张量元素数目
'''

print(image_in.numel())

4704


In [12]:
'''
torch.FloatTensor的输入作用
'''

#生成指定张量
t1 = torch.FloatTensor([1.2, 4.3])  ##不推荐使用
print(t1)

#生成指定形状的张量，未初始化
t2 = torch.FloatTensor(1, 2, 3)
print(t2)

tensor([1.2000, 4.3000])
tensor([[[-9.0406e-23,  4.5915e-41,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [13]:
'''
均匀采样0-10的随机张量
'''

t_test = 10 * torch.rand(3, 3)
print(t_test)

tensor([[5.3894, 8.8334, 2.3138],
        [0.9652, 6.2210, 1.5272],
        [5.6017, 4.9012, 4.7157]])


In [15]:
'''
生成来自于10均值为0，方差不同的正态分布[2,5]张量
'''

t = torch.normal(mean=torch.full([10], 0),
                 std=torch.arange(1, 0, -0.1)).view(2, 5)  ##tensor没有reshape
print(t)

tensor([[-0.9956,  0.8989,  1.1733,  0.4062, -0.5954],
        [ 0.1560, -0.1922, -0.5187,  0.1533,  0.0540]])


In [3]:
'''
乱序索引
'''

a = torch.rand(4, 3)
b = torch.tensor([[0.], [1.], [2.0], [3.0]])
print(b.shape)
c = torch.cat([b, a], dim=1)
print(c)
print(c.shape)

torch.Size([4, 1])
tensor([[0.0000, 0.5155, 0.0424, 0.5071],
        [1.0000, 0.2075, 0.6843, 0.6519],
        [2.0000, 0.2202, 0.4358, 0.5101],
        [3.0000, 0.3082, 0.2753, 0.2088]])
torch.Size([4, 4])


In [4]:
idx = torch.randperm(4)
print(idx)
c[idx]  # 这个相当于换行 索引第1行，第2行，第3行，第0行

tensor([1, 2, 3, 0])


tensor([[1.0000, 0.2075, 0.6843, 0.6519],
        [2.0000, 0.2202, 0.4358, 0.5101],
        [3.0000, 0.3082, 0.2753, 0.2088],
        [0.0000, 0.5155, 0.0424, 0.5071]])