## 张量高级操作

**1. 张量的拼接与合并操作**

    torch.cat(tensor, dim=0, out=None)

- 功能

    将张量按维度dim进行拼接

- tensors

    张量序列
 
- dim

    要拼接的维度
    

    torch.stack(tensors, dim=0, out=None)

- 功能

    在新创建的维度上dim进行拼接


- 注意

    cat不改变张量的维度，即合并以后，向量是向量，矩阵是矩阵
    
    stack会扩充一维

In [1]:
import torch

In [4]:
# ======================================= example 1 =======================================
# torch.cat

t = torch.ones((2, 3))
print(t.shape)
t_ca = torch.cat([t, t], dim=0)
print(t_ca.shape)
t_ca1 = torch.cat([t, t], dim=1)
print(t_ca1.shape)

torch.Size([2, 3])
torch.Size([4, 3])
torch.Size([2, 6])


In [18]:
# ======================================= example 2 =======================================
# torch.stack

t = torch.zeros((4, 5))
print(t.shape)
t_st = torch.stack([t, t], dim=2) ##在非指定维度上shape必须一致
print(t_st.shape)
print(t_st)

torch.Size([4, 5])
torch.Size([4, 5, 2])
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])


**2. 张量切分**

    torch.chunk(input, chunks, dim=0)

- 功能

    将张量按维度dim进行平均切分
    
    
- input
    
    要切分的张量

- chunks

    要切分的份数

- dim 

    要切分的维度
    
- 输出

    张量列表


    torch.split(tensor, split_size_or_sections, dim=0)

- 功能

    将张量按维度dim进行切分

- tensor

    要切分的张量

- split_size_or_sections

    指定切分的tensor在dim维的长度，可以为int或list

- dim

    切分的维度
    
- 输出

    张量列表

区分：
- torch.split()对于随意切分更为强大
- torch.chunk()对于平均切分更为强大

In [24]:
# ======================================= example 3 =======================================
# torch.chunk

t = torch.ones((3, 4))
print(t.shape)
t_1 = torch.chunk(t, 2, dim=0)
print(t_1[0].shape)
print(t_1)

t_2 = torch.chunk(t, 2, dim=1)
print(t_2)
print(t_2[0].shape)

torch.Size([3, 4])
torch.Size([2, 4])
(tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]), tensor([[1., 1., 1., 1.]]))
(tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]), tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]))
torch.Size([3, 2])


In [25]:
# ======================================= example 4 =======================================
# torch.split

t = torch.ones((2, 5))

list_of_tensors = torch.split(t, [2, 1, 2], dim=1)

for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}\n维度为：{}".format(idx + 1, t, t.shape))

第1个张量：tensor([[1., 1.],
        [1., 1.]])
维度为：torch.Size([2, 2])
第2个张量：tensor([[1.],
        [1.]])
维度为：torch.Size([2, 1])
第3个张量：tensor([[1., 1.],
        [1., 1.]])
维度为：torch.Size([2, 2])


**3. 张量索引**

    torch.index_select(input, dim, index, out=None)

- 功能

    在维度dim上，按index索引数据
    
- input
    
    要索引的张量

- index

    要索引数据的序号(此处必须为张量)
    
- 输出

    根据索引的张量拼接成新张量

总结：

- 按维度切分索引重组张量


    torch.masked_select(input, mask, out=None)

- 功能

    按mask的True值进行索引

- input

    索引的张量

- mask

    与input相同大小的布尔型张量

- 输出

    一维张量


    torch.take(input,index)
    
 - 功能
 
     将input拉成一维后，依据index索引

**总结：**

- 该方法常用来筛选数据

In [2]:
# ======================================= example 5 =======================================
# torch.index_select

t = torch.randint(0, 9, (3, 3))
print(t)
idx = torch.tensor([0, 2], dtype=torch.long)  # 注意必须是long类型
t_out = torch.index_select(t, dim=0, index=idx)
print(t_out)

tensor([[7, 2, 0],
        [3, 3, 7],
        [7, 1, 0]])
tensor([[7, 2, 0],
        [7, 1, 0]])


In [3]:
# ======================================= example 6 =======================================
# torch.masked_select

t = torch.randint(0, 9, (3, 3))
print(t)
mask = t.le(5)  ##ge:大于等于 gt：大于  le：小于等于  lt:小于
print(mask)
t_out = torch.masked_select(t, mask)
print(t_out)

tensor([[5, 3, 0],
        [3, 8, 6],
        [2, 3, 2]])
tensor([[ True,  True,  True],
        [ True, False, False],
        [ True,  True,  True]])
tensor([5, 3, 0, 3, 2, 3, 2])


In [4]:
torch.masked_select(t, t <= 5)

tensor([5, 3, 0, 3, 2, 3, 2])

In [4]:
# ======================================= example 6，ex =======================================
# torch.take()

input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
out = torch.take(input_tensor, torch.tensor([1, 2, 4]))
print(out)

tensor([2, 3, 5])


**3. 张量变换**

    torch.reshape(input__, shape)

- 功能

    变换张量形状

注意：
- 生成的新张量与input共享内存

- 同 torch.view(shape)



In [2]:
# ======================================= example 7 =======================================
# torch.reshape

t = torch.randperm(6)
print("tensor:{}\nshape:{}".format(t, t.shape))
t_new = torch.reshape(t, (2, 3))
print("tensor:{}".format(t_new, t_new.shape))

t.reshape(2,3)##pytorch支持reshape操作

tensor:tensor([2, 1, 4, 5, 3, 0])
shape:torch.Size([6])
tensor:tensor([[2, 1, 4],
        [5, 3, 0]])


tensor([[2, 1, 4],
        [5, 3, 0]])

    torch.transpose(input, dim0, dim1)

- 功能

    交换张量的两个维度
    
- 维度交换

    dim0与dim1的交换
    
        
    torch.t(input)

- 功能

    矩阵转置
    
- input

    输入张量

    
    torch.permute(shape)
    
 - 功能
 
     交换多维度数据
     
- shape

    交换维度索引

In [8]:
# ======================================= example 8 =======================================
# torch.transpose

t = torch.rand((2, 3, 4))

t_new = t.transpose(0, 1)  #交换第0维和第1维
#t_new = torch.transpose(t, 0, 1)
print("t_new:{}\nt.shape:{}".format(t_new, t_new.shape))

t_new:tensor([[[0.4810, 0.1906, 0.2812, 0.0878],
         [0.5002, 0.2034, 0.0218, 0.4748]],

        [[0.8578, 0.5265, 0.4688, 0.2204],
         [0.2340, 0.2548, 0.9366, 0.8606]],

        [[0.8620, 0.5528, 0.3955, 0.8683],
         [0.5050, 0.7317, 0.6520, 0.4701]]])
t.shape:torch.Size([3, 2, 4])


In [19]:
# ======================================= example 8 =======================================
# torch.permute(shape)

ta = torch.rand(4, 3, 28, 28)
t_per = ta.permute(0, 2, 3, 1)
print(t_per.shape)

torch.Size([4, 28, 28, 3])


    torch.squeeze(input, dim=None, out=None)

- 功能

    压缩长度为1的维度
    
- dim

    若为None,移除所有长度为1的维度；若指定维度，则该维度为1时才能被移除

       
    torch.unsqueeze(input, dim, out=None)

- 功能

    按给定的dim扩展维度


In [13]:
# ======================================= example 9 =======================================
# torch.squeeze

##压缩维度
t = torch.rand((1, 2, 3, 4, 1))
t_new = torch.squeeze(t)
t_new1 = torch.squeeze(t, 0)
print("t_new:{}\nt_new1:{}".format(t_new.shape, t_new1.shape))
print("-------------------------------------------------")
##扩展维度
#t_new2 = torch.unsqueeze(t)  报错
t_new2 = torch.unsqueeze(t, 0)
t_new3 = torch.unsqueeze(t, 2)
#t_new3.squeeze(1)
print("t_new:{}\nt_new3:{}".format(t_new2.shape, t_new3.shape))

t_new:torch.Size([2, 3, 4])
t_new1:torch.Size([2, 3, 4, 1])
-------------------------------------------------
t_new:torch.Size([1, 1, 2, 3, 4, 1])
t_new3:torch.Size([1, 2, 1, 3, 4, 1])


In [11]:
'''
实例：图像每个channel的像素加入同一偏置
'''

bias = torch.rand(32)  ##行向量
print(bias)
print(bias.shape)

feature_map = torch.rand((4, 32, 14, 14))
bias = bias.unsqueeze(0).unsqueeze(2).unsqueeze(3)
print(bias.shape)
print(bias)

tensor([0.3088, 0.9499, 0.0301, 0.5402, 0.8294, 0.7973, 0.1331, 0.6130, 0.0182,
        0.7742, 0.4424, 0.0331, 0.7472, 0.2194, 0.1493, 0.7731, 0.0331, 0.6624,
        0.7383, 0.1993, 0.8565, 0.2723, 0.6428, 0.3015, 0.8910, 0.9328, 0.2901,
        0.6332, 0.5741, 0.5167, 0.8041, 0.3521])
torch.Size([32])
torch.Size([1, 32, 1, 1])
tensor([[[[0.3088]],

         [[0.9499]],

         [[0.0301]],

         [[0.5402]],

         [[0.8294]],

         [[0.7973]],

         [[0.1331]],

         [[0.6130]],

         [[0.0182]],

         [[0.7742]],

         [[0.4424]],

         [[0.0331]],

         [[0.7472]],

         [[0.2194]],

         [[0.1493]],

         [[0.7731]],

         [[0.0331]],

         [[0.6624]],

         [[0.7383]],

         [[0.1993]],

         [[0.8565]],

         [[0.2723]],

         [[0.6428]],

         [[0.3015]],

         [[0.8910]],

         [[0.9328]],

         [[0.2901]],

         [[0.6332]],

         [[0.5741]],

         [[0.5167]],

        

    tensor.expand(shape)
 
- 功能

    通过复制数据，常用扩展数据方法
    
    
    tensor.repeat(shape)

- 功能

    复制数据扩展维度，shape为复制的倍数

In [15]:
# ======================================= example 9 =======================================
# tensor.expand(shape)

t1 = torch.rand(1, 8, 1, 1)
print(t1)
tb = t1.expand(4, 8, 4, 4)  ## 仅限于原维度是1的地方
print(tb)
tc = t1.expand(-1, 8, 6, -1)  ## 默认维度
print(tc.shape)

tensor([[[[0.1221]],

         [[0.9505]],

         [[0.4238]],

         [[0.7995]],

         [[0.8554]],

         [[0.7853]],

         [[0.2167]],

         [[0.1125]]]])
tensor([[[[0.1221, 0.1221, 0.1221, 0.1221],
          [0.1221, 0.1221, 0.1221, 0.1221],
          [0.1221, 0.1221, 0.1221, 0.1221],
          [0.1221, 0.1221, 0.1221, 0.1221]],

         [[0.9505, 0.9505, 0.9505, 0.9505],
          [0.9505, 0.9505, 0.9505, 0.9505],
          [0.9505, 0.9505, 0.9505, 0.9505],
          [0.9505, 0.9505, 0.9505, 0.9505]],

         [[0.4238, 0.4238, 0.4238, 0.4238],
          [0.4238, 0.4238, 0.4238, 0.4238],
          [0.4238, 0.4238, 0.4238, 0.4238],
          [0.4238, 0.4238, 0.4238, 0.4238]],

         [[0.7995, 0.7995, 0.7995, 0.7995],
          [0.7995, 0.7995, 0.7995, 0.7995],
          [0.7995, 0.7995, 0.7995, 0.7995],
          [0.7995, 0.7995, 0.7995, 0.7995]],

         [[0.8554, 0.8554, 0.8554, 0.8554],
          [0.8554, 0.8554, 0.8554, 0.8554],
          [0.8554, 0.85

In [16]:
# ======================================= example 9 =======================================
# tensor.repeat(shape)

t1=torch.rand(1,32,1,1)
print(t1.shape)
t2=t1.repeat(2,32,1,3)
print(t2.shape)

torch.Size([1, 32, 1, 1])
torch.Size([2, 1024, 1, 3])


## 张量的数学运算

**加法**

    torch.add()  ## a+b

**减法**

    torch.sub()   ## -

**除法**

    torch.div()   ## /

**乘法**

    torch.mul()   ## *

以加法为例：

    torch.add(input, alpha=1, other, out=None)

- 功能

    逐元素计算input+alpha*other
    
- other

    另一个张量
    
     
     torch.addcmul(input, value, tensor1, tensor2, out=None)

- 功能

    计算input+value\*tensor1\*tensor2
    
     
     torch.addcdiv(input, value, tensor1, tensor2, out=None)

- 功能

    计算input+value\*tensor1/tensor2

In [4]:
# ======================================= example 8 =======================================
# torch.add

t_0 = torch.randint(0, 9, (3, 3))
t_1 = torch.full_like(t_0, 3)
print("t_0:{}\nt_1:{}".format(t_0, t_1))

t_result = torch.add(t_0, t_1)
#t_result = torch.add(t_0, 1, t_1)
print("t_result:{}".format(t_result))

t_0:tensor([[8, 1, 5],
        [2, 1, 0],
        [0, 0, 4]])
t_1:tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])
t_result:tensor([[11,  4,  8],
        [ 5,  4,  3],
        [ 3,  3,  7]])


    torch.matmul(a,b)
    
- 功能

    矩阵乘法
    
    
    a@b

In [2]:
# ======================================= example 8 =======================================
# torch.matmul

a=torch.full((2,2),3)
print(a)
b=torch.ones(2,2)
print(b)
print(torch.matmul(a,b))

tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])


**对数运算运算**

    torch.log(input, out=None)

    torch.log10(input)

    torch.log2(input)

    torch.exp(input)

    torch.pow()

In [6]:
# ======================================= example 8 =======================================
# =============== pow

a = torch.full((2, 2), 3)
print(a)
a.pow_(2)  # 加引号表示原地操作
print(a)
a.exp_()
print(a)
a.log_()
print(a)

tensor([[3., 3.],
        [3., 3.]])
tensor([[9., 9.],
        [9., 9.]])
tensor([[8103.0840, 8103.0840],
        [8103.0840, 8103.0840]])
tensor([[9., 9.],
        [9., 9.]])


**近似计算**

    floor 
    ceil
    trunc ##整数 
    frac  ##小数
    round ##四舍五入
    clamp(min,max)  ##将数据限制在min和max之间

In [9]:
a=torch.rand(2,3)
a.floor()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
a.trunc()

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
a.round()

tensor([[0., 0., 1.],
        [1., 1., 1.]])

In [12]:
a.frac()  

tensor([[0.2237, 0.4241, 0.6359],
        [0.5164, 0.8182, 0.6305]])

In [15]:
a.clamp(0.2,0.5)

tensor([[0.2237, 0.4241, 0.5000],
        [0.5000, 0.5000, 0.5000]])

**三角函数运算**

    torch.abs(input)

    torch.cos(input)

    torch.acos(input)

    torch.sin(input)

    torch.asin(input)

    torch.tan(input)

    torch.atan(input)


## 张量统计运算

    norm()  
        范数运算
    
    mean()   sum()        prod()  累乘
    
    max()    min()   取最大最小
    
    argmax()   argmin()   取最大最小索引
    
    kthvalue()   topk()

In [19]:
# ======================================= example =======================================
# =============== norm

t1 = torch.full([8], 1).view(1, 8)
t2 = t1.view(2, 4)
print(t1)
print(t2)

print(t1.norm(1))  ## 1范数
print(t1.norm(2))  ## 2范数
print(t2.norm(1, dim=0))
print(t2.norm(2, dim=1))

tensor([[1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor(8.)
tensor(2.8284)
tensor([2., 2., 2., 2.])
tensor([2., 2.])


In [20]:
# ======================================= example =======================================
# =============== a.sum(),a.mean(),a.max(),a.prod()
a = torch.arange(8).view(2, 4).float()
print(a.sum(), a.mean(), a.max(), a.prod())

tensor(28.) tensor(3.5000) tensor(7.) tensor(0.)


In [24]:
# ======================================= example =======================================
# =============== a.argmax(),a.argmin()
print(a)
print(a.argmax(), a.argmin())  # 拉平一维后的索引
print(a.argmax(dim=0))
print(a.argmin(dim=1))
print(a.max(dim=1))  #既返回最大值又返回最值索引

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])
tensor(7) tensor(0)
tensor([1, 1, 1, 1])
tensor([0, 0])
(tensor([3., 7.]), tensor([3, 3]))


In [27]:
# ======================================= example =======================================
# =============== keepdim  保证向量，矩阵，张量的dim
b = a.max(dim=1, keepdim=True)
print(b)
print(a.shape)
print(b[0].shape)

(tensor([[3.],
        [7.]]), tensor([[3],
        [3]]))
torch.Size([2, 4])
torch.Size([2, 1])


    前k个最大
    topk(k,dim=0,argest=True)  
        - argest=True表示最大
    
    第k个最大
    kthvalue(k,dim=0,argest=True)

In [3]:
# ======================================= 实例返回 top-5 类别=======================================
# =============== topk

imgdata = torch.rand(4, 10)
label = imgdata.topk(5, dim=1)
print(label[0].shape)
print(label)

torch.Size([4, 5])
(tensor([[0.8951, 0.6925, 0.6097, 0.5674, 0.4667],
        [0.9740, 0.8699, 0.8377, 0.8263, 0.6641],
        [0.9107, 0.8429, 0.6788, 0.6717, 0.6648],
        [0.9699, 0.9376, 0.9242, 0.8082, 0.7893]]), tensor([[2, 4, 9, 3, 1],
        [1, 5, 2, 0, 8],
        [4, 1, 8, 3, 2],
        [3, 1, 6, 4, 9]]))


In [2]:
# ======================================= 实例返回 top-5 类别=======================================
# =============== topk

imgdata = torch.rand(4, 10)
label = imgdata.kthvalue(5, dim=1)
print(label)

(tensor([0.3376, 0.3876, 0.1701, 0.1607]), tensor([9, 9, 8, 2]))
