## Pytorch中的高阶OP

    torch.where(condition,x,y)
    
    if conditon:
        x
    else:
        y

In [5]:
import torch

In [4]:
#======================================= 设置概率值 ===================================================
# =======================================where

A = torch.full((2, 2), 1)
B = torch.full((2, 2), 0)
data = torch.rand((2, 2))
result = torch.where(data > 0.5, A, B)
print(A)
print(B)
print(data)
print(result)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.7933, 0.4137],
        [0.3752, 0.5107]])
tensor([[1., 0.],
        [0., 1.]])


## 激活函数

    sigmoid()
    
    tanh()
    
    relu()

In [6]:
# ============================================ sigmoid   =================================================

a = torch.linspace(-100, 100, 10)
print(a.sigmoid())

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])


In [7]:
def sigmoid_derivative(x):
    return x.sigmoid() * (1 - x.sigmoid())


print(sigmoid_derivative(a))

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 1.4901e-05,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])


In [8]:
b = torch.linspace(-1, 1, 10)
print(b.tanh())

tensor([-0.7616, -0.6514, -0.5047, -0.3215, -0.1107,  0.1107,  0.3215,  0.5047,
         0.6514,  0.7616])


In [9]:
print(b.relu())

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1111, 0.3333, 0.5556, 0.7778,
        1.0000])


## 自动求导机制